#!/usr/bin/perl
use strict;
use warnings;

sub backup($);

my $dir = "$ENV{HOME}/Code/n9";

my $host = `n9`;
chomp $host;

sub main(@){
  die "Usage: $0\n" if @_ != 0;
  print "making sure n9 is ssh-able\n";
  system "n9", "-s", "echo found n9!\n";
  die "failed" if $? != 0;

  backup "dcim-backup";
  backup "sync-pixmirror";

  backup "sync-mydocs";
  backup "sync-fbreader backup";
  backup "fetch-klomp-lists backup";
  backup "sync-swype backup";
  backup "sync-qtodo";
  backup "fetch-contacts";
  backup "fetch-comm call";
  backup "fetch-comm sms";
  system "klomp-sync user@`n9` --nopresync";
}

sub backup($){
  my $backupScript = shift;

  print "\n\n\n=========$backupScript\n";
  system "$dir/$backupScript";

  die "$backupScript failed" if $? != 0;
}

&main(@ARGV);
