#!/usr/bin/perl
use strict;
use warnings;

my $dir = "$ENV{HOME}/Code/n9";

my $host = `n9`;
chomp $host;

print "getting sudo pw cached\n";
system "sudo", "echo", "ok";
die "failed" if $? != 0;

system "$dir/dcim-backup";
die "failed" if $? != 0;

system "$dir/sync-pidgin";
die "failed" if $? != 0;
system "$dir/sync-mydocs";
die "failed" if $? != 0;
system "$dir/sync-fbreader backup";
die "failed" if $? != 0;
system "$dir/sync-qtodo backup";
die "failed" if $? != 0;

system "$dir/fetch-contacts";
die "failed" if $? != 0;
system "$dir/fetch-sms";
die "failed" if $? != 0;

