#!/usr/bin/perl
use strict;
use warnings;

my $dir = "$ENV{HOME}/Code/n9";

sub run(@){
  print "@_\n";
  system @_;
}

run "n9", "-s", "umount -l /home/user/MyDocs";
print "sleeping for 2 sex, then ill prompt you to continue\n";
sleep 2;
print "\n\n\n";
print "ok muthafucka. you ready?! are you HARD enough?!??\n";
print "THIS WILL KILL MyDocs, DCIM, AND YO BABY [y/N]: ";
if(lc <STDIN> ne "y\n"){
  die "what a fag!\n";
}
print "oooooookay you one tough muthafucka\n";
print "this will probably either:\n";
print "  take 1min to produce any output, then another 1min to finish\n";
print "  OR fail immediately\n";
print "\n\n\n";

#run "n9", "-s", "mkfs.ext4 /dev/mmcblk0p1";

print "\n\n";
print "DID THAT SHIT WORKK!?!?! [y/N]: ";
if(lc <STDIN> ne "y\n"){
  die "fucken TOLEJA\n";
}

run "n9", "-s", "mount -t ext4 /dev/mmcblk0p1 /home/user/MyDocs";

run "$dir/ext4-mydocs-fstab";
