#!/usr/bin/perl
use strict;
use warnings;

my $dir = "$ENV{HOME}/Code/n9";
my $dest = "$dir/backup";

my $host = `n9`;
chomp $host;

my $smsSrcDir = "/home/user/MyDocs/backup-sms";
my $smsDestDir = "$dest/backup-sms";

sub run(@){
  print "@_\n";
  system @_;
}
sub runOrDie(@){
  run @_;
  die "failed" if $? != 0;
}

run "n9", "-s", "killall -9 smsbackuprestore";
run "n9", "-s", "/opt/dropcache-mdn/bin/dropcache.sh --3";
runOrDie "n9", "-b", "backup-sms";
runOrDie "mkdir", "-p", $smsDestDir;
runOrDie "rsync", "-avP", "root\@$host:$smsSrcDir/", $smsDestDir;
runOrDie "perl $dir/sms-tool.pl split";
runOrDie "perl $dir/sms-tool.pl commit";

