#!/usr/bin/perl
use strict;
use warnings;

my $dir = "$ENV{HOME}/Code/n9";
my $dest = "$dir/backup";

my $host = `n9`;
chomp $host;

my $smsSrcDir = "/home/user/MyDocs/backup-sms";
my $smsDestDir = "$dest/backup-sms";

sub run(@){
  print "@_\n";
  system @_;
  die "failed" if $? != 0;
}

run "n9", "-s", "backup-sms";
run "mkdir", "-p", $smsDestDir;
run "rsync", "-avP", "root\@$host:$smsSrcDir/", $smsDestDir;
run "perl $dir/sms-tool.pl split";
run "perl $dir/sms-tool.pl commit";

