#!/usr/bin/perl
use strict;
use warnings;

sub run(@);
sub runOrDie(@);

my $MODE_N9E = "n9-export";
my $MODE_SCBR = "sms-call-backup-restore";

my $defaultSmsMode = $MODE_N9E;
my $defaultCallMode = $MODE_SCBR;

my $usage = "Usage:
  $0 sms
    backup SMS

  $0 call
    backup calls
";

sub main(@){
  my $type = shift() || '';
  die $usage if $type !~ /^(sms|call)$/ or @_ > 0;

  my $dir = "$ENV{HOME}/Code/n9";
  my $dest = "$dir/backup";
  my $parseTool = "comm-tool.pl $type";

  my $host = `n9`;
  chomp $host;

  my $srcDir = "/home/user/MyDocs/backup-$type";
  my $destDir = "$dest/backup-$type";

  my $remoteRepoDir = "$srcDir-repo";

  my $mode;
  $mode = $defaultSmsMode if $type eq "sms";
  $mode = $defaultCallMode if $type eq "call";

  if($mode eq $MODE_N9E){
    runOrDie "n9", "-b", "backup-comm-n9e $type";
  }elsif($mode eq $MODE_SCBR){
    my $scbrExec = "${type}backuprestore";
    run "n9", "-s", "killall -9 $scbrExec";
    run "n9", "-s", "/opt/dropcache-mdn/bin/dropcache.sh --3";
    runOrDie "n9", "-b", "backup-comm-scbr $type --retry 20";
  }

  runOrDie "mkdir", "-p", $destDir;
  runOrDie "rsync", "-avP", "root\@$host:$srcDir/", $destDir;
  runOrDie "perl $dir/$parseTool split";
  runOrDie "perl $dir/$parseTool commit";
  runOrDie "perl $dir/$parseTool join-all";

  run "scp", "$destDir/all.$type", "root\@$host:$srcDir/";
  run "n9", "-s", "chown user.users -R $srcDir/all.$type";
  run "rsync", "-a", "$destDir/repo/", "root\@$host:$remoteRepoDir/";
  run "n9", "-s", "chown user.users -R $remoteRepoDir";
}

sub run(@){
  print "@_\n";
  system @_;
}
sub runOrDie(@){
  run @_;
  die "failed" if $? != 0;
}

&main(@ARGV);
