#!/usr/bin/perl
use strict;
use warnings;

sub run(@);

my $dir = "$ENV{HOME}/Code/n9";
my $localDir = "$dir/backup/klomp";
my $remoteDir = "/home/user/.klomp";

my @rsyncOpts = qw(
  -avP --no-owner --no-group --no-perms
);
my @excludes = qw(
  db
  datecache
  lib
);

sub main(@){
  die "Usage: $0 [backup|restore]\n" if @_ != 1 or $_[0] !~ /^(backup|restore)$/;
  my $arg = shift();

  my $host = `n9`;
  chomp $host;

  for my $exclude(@excludes){
    push @rsyncOpts, "--exclude=$exclude";
  }

  if($arg eq 'backup'){
    system "rm", "-r", $localDir;
    system "mkdir", "-p", $localDir;
    run "rsync", @rsyncOpts, "user\@$host:$remoteDir/", $localDir;
  }elsif($arg eq 'restore'){
    run "rsync", @rsyncOpts, "$localDir/", "user\@$host:$remoteDir/";
  }
}

sub run(@){
  print "@_\n";
  system @_;
  die "failed" if $? != 0;
}

&main(@ARGV);
