#!/usr/bin/perl
use strict;
use warnings;

my $destDir = "$ENV{HOME}/Code/n9/backup/backup-contacts";
my $srcDir = "/home/user/MyDocs/backup-contacts";

sub run(@);

sub main(@){
  my $host = `n9`;
  chomp $host;

  run "n9", "-s", "backup-contacts";
  run "mkdir", "-p", $destDir;
  run "rsync", "-avP", "root\@$host:$srcDir/", $destDir;
}

sub run(@){
  print "@_\n";
  system @_;
  die "FAILED: @_\n" if $? != 0;
}

&main(@ARGV);
