#!/usr/bin/perl
use strict;
use warnings;

my $dir = "$ENV{HOME}/Code/n9";
my $dest = "$dir/backup";

my $host = `n9`;
chomp $host;

my $callsSrcDir = "/home/user/MyDocs/backup-calls";
my $callsDestDir = "$dest/backup-calls";

sub run(@){
  print "@_\n";
  system @_;
}
sub runOrDie(@){
  run @_;
  die "failed" if $? != 0;
}

run "n9", "-s", "killall -9 callsbackuprestore";
run "n9", "-s", "/opt/dropcache-mdn/bin/dropcache.sh --3";
runOrDie "n9", "-b", "backup-calls";
runOrDie "mkdir", "-p", $callsDestDir;
runOrDie "rsync", "-avP", "root\@$host:$callsSrcDir/", $callsDestDir;
runOrDie "perl $dir/calls-tool.pl split";
runOrDie "perl $dir/calls-tool.pl commit";

