#!/usr/bin/perl
use strict;
use warnings;

sub listInt($);
my $lockScreenBG = '/usr/share/backgrounds/lockscreen.jpg';

my $display = '/system/osso/dsm/display';
my $locks = '/system/osso/dsm/locks';
my %gconf = (
  "/Meego/System/UsbMode" => ['ovi_suite'],
  "/desktop/meego/background/portrait/picture_filename" => [$lockScreenBG],
  "$locks/tklock_double_tap_gesture" => ['0', 'int'],
  "$display/display_dim_timeout" => [240,'int'],
  "$display/possible_display_dim_timeouts" =>
    listInt [15, 30, 60, 120, 180, 240],

);

sub gconfGetCmd($){
  return "gconftool-2 --get $_[0]";
}
sub gconfSetCmd($$$$){
  my ($key, $val, $type, $listType) = @_;
  my $cmd = "gconftool-2 --set '$key' '$val' --type=$type";
  if(lc $type eq 'list'){
    $cmd .= " --list-type=$listType";
  }
  return $cmd;
}
sub listInt($){
  my @list = @{shift()};
  my $val = '[' . (join ',', @list) . ']';
  return [$val, 'list', 'int'];
}

sub main(@){
  die "Usage: $0\n" if @_ > 0;
  my @cmds = ();
  for my $key(keys %gconf){
    my @arr = @{$gconf{$key}};
    my $val = shift @arr;
    my $type = @arr > 0 ? shift @arr : 'string';
    my $listType = @arr > 0 ? shift @arr : undef;
    push @cmds, "echo -n \"$key| NEW: $val OLD: \"";
    push @cmds, gconfGetCmd($key);
    push @cmds, gconfSetCmd($key, $val, $type, $listType);
  }
  my $cmd = join "\n", @cmds;
  print "$cmd\n\n";
  system "n9", "-s", $cmd;
}
&main(@ARGV);
