#!/usr/bin/perl
use strict;
use warnings;

my $gitRepo = "git://github.com/teleshoes/qtemail.git";

sub run(@){
  print "@_\n";
  system @_;
}

run "n9", "-b", "
  if [ -e /root/qtemail ]; then
    echo updating qtemail git repo
    cd /root/qtemail
    git pull
  else
    echo fetching qtemail git repo
    cd /root
    git clone $gitRepo
  fi
  echo running qtemail install
  cd /root/qtemail
  ./install.pl /usr
";
