#!/usr/bin/perl
use strict;
use warnings;

my $depsDir = "$ENV{HOME}/Code/n9/klomp";
my $gitRepo = "git://github.com/teleshoes/klomp.git";

sub run(@){
  print "@_\n";
  system @_;
}

run "n9u", "-b", "mkdir /home/user/.klomp";
run "scp $depsDir/lib user\@`n9`:/home/user/.klomp/";

run "n9", "-b", "
  if [ -e /root/klomp ]; then
    echo updating klomp git repo
    cd /root/klomp
    git pull
  else
    echo fetching klomp git repo
    cd /root
    git clone $gitRepo
  fi
  echo running klomp install
  cd /root/klomp
  ./install.pl /usr
";
