#!/usr/bin/perl
use strict;
use warnings;

my $gitRepo = "git://github.com/teleshoes/n9-button-monitor.git";

sub run(@){
  print "@_\n";
  system @_;
}

run "n9", "-b", "
  if [ -e /root/n9-button-monitor ]; then
    echo updating n9-button-monitor git repo
    cd /root/n9-button-monitor
    git pull
  else
    echo fetching n9-button-monitor git repo
    cd /root
    git clone $gitRepo
  fi
  echo running n9-button-monitor install
  cd /root/n9-button-monitor
  ./install.sh
";
