#!/usr/bin/perl
use strict;
use warnings;

my @buttons = qw(
  call-history
  messaging-ui
  meego-terminal
  fennec 

  pidgin
  klomp
  meecast
  camera-ui

  nokia-drive-qml
  xmcr
  vmpkn9
  FBReader
  
  calendar
  clock
  gallery
  duicontrolpanel
  
  gconfik_harmattan
  contacts
  calc
  joikuspot
  
  notes
  mail
  accountsui
);

my @quickLaunch = qw(
  call-history
  messaging-ui
  fennec 
  camera-ui
);

my $host = `n9`;
chomp $host;

my $appDir = '/usr/share/applications';
my $unusedDir = '/opt/unused-applications';
my $quickLaunchDir = '/home/user/.local/share/applications';
my $confFileDest = '/home/user/.config/meegotouchhome-nokia/launcherbuttons.data';


system "n9", "-s", "
  set -x
  mkdir -p $unusedDir
  cd $appDir
  bash -c 'find -maxdepth 1 -name \\*.desktop -execdir mv {} $unusedDir \\;'
  rm -rf $appDir
  mkdir -p $appDir
";

my $cmd = "cd $unusedDir; mv";
for my $button(@buttons){
  $cmd .= " $button.desktop";
}
$cmd .= " $appDir";
print $cmd;
system "ssh", "root\@$host", $cmd;


my $confFile = "[DesktopEntries]
home\\user\\.local\\share\\applications\\quicklaunchbar0.desktop=quicklaunchbar/0
home\\user\\.local\\share\\applications\\quicklaunchbar1.desktop=quicklaunchbar/1
home\\user\\.local\\share\\applications\\quicklaunchbar2.desktop=quicklaunchbar/2
home\\user\\.local\\share\\applications\\quicklaunchbar3.desktop=quicklaunchbar/3
";

for(my $i=0; $i<@buttons; $i++){
  my $button = $buttons[$i];
  my $line = "usr\\share\\applications\\$button.desktop=launcher/0/$i\n";
  $confFile .= $line;
}

$cmd = "\n";
$cmd .= "rm $quickLaunchDir/*.desktop;\n";
for(my $i=0; $i<@quickLaunch; $i++){
  my $qlFile = "$quickLaunchDir/quicklaunchbar$i.desktop";
  $cmd .= "ln -s $appDir/$quickLaunch[$i].desktop $qlFile;\n";
}
print $cmd;
system "ssh", "root\@$host", $cmd;

print $confFile;
my $tmp = "/tmp/launcherbuttons.data";
open FH, "> $tmp" or die "Couldnt write to $tmp\n";
print FH $confFile;
close FH;

system "ssh root\@$host killall meegotouchhome";
system 'scp', $tmp, "root\@$host:$confFileDest";

