#!/usr/bin/perl
use strict;
use warnings;

sub main(@){
  my @files = qw(
     /home/user/.aegis
     /home/user/.accounts
     /home/user/.activesync
     /etc/aegisfs.d/*.*
  );
  my $certsBak = "/root/certs.bak." . time;

  print "backing up ssl certs and destroying aegis\n";
  system "n9", "-s", "
    set -x
    rm -rf $certsBak
    cp -ar /etc/ssl/certs $certsBak;
    rm -rf @files
    ";
  die "failed!\n" unless $? == 0;

  print "rebooting..\n";
  system "n9", "-s", "/sbin/reboot";

  print "waiting for n9\n";
  print "sleeping for 20\n";
  sleep 20;
  print "attempting ssh: ";

  my $old_fh = select(STDOUT); $| = 1; select($old_fh);
  my $hostname = `n9`;
  chomp $hostname;

  my $ok = 0;
  while(not $ok){
    print ".";
    my $cmd = "ssh user\@$hostname"
      . " -o ConnectTimeout=2"
      . " echo -n hello 2>/dev/null"
      ;
    $ok = 1 if `$cmd` eq "hello";
    sleep 1 unless $ok;
  }
  print "\nok!\n";

  print "restoring ssl certs\n";
  system "n9", "-s", "
    set -x
    rm -rf /etc/ssl/certs
    cp -ar $certsBak /etc/ssl/certs
  ";
}

&main(@ARGV);
