#!/usr/bin/perl
use strict;
use warnings;

my $repo = "$ENV{HOME}/Code/n9/backup/backup-contacts/repo";

sub run(@);

sub main(@){
  my $host = `n9`;
  chomp $host;

  my $file = "contacts.vcf";
  die "$repo/$file not found\n" if not -e "$repo/$file";

  run "scp", "$repo/$file", "root\@$host:/tmp";
  run "n9", "-s", "source /etc/profile; vcardconverter /tmp/$file";

  print "you may want to now run merge contacts and delete unnamed\n";
}

sub run(@){
  print "@_\n";
  system @_;
  die "FAILED: @_\n" if $? != 0;
}

&main(@ARGV);
