#!/usr/bin/perl
use strict;
use warnings;

sub run(@){
  print "@_\n";
  system @_;
}

sub main(@){
  my $host = `n9`;
  chomp $host;
  run "rsync", "-avP",
    "--exclude=status",
    "$ENV{HOME}/openvpn",
    "user\@$host:/home/user";
  run "scp", "$ENV{HOME}/.twip", "user\@$host:/home/user";
  run "scp", "$ENV{HOME}/.secrets", "user\@$host:/home/user";

  run "n9", "
    cd /home/user/openvpn
    rm client.pem client.pem.default
    ln -s client.pem.wolke-n9 client.pem
    ln -s client.pem.wolke-n9 client.pem.default
  ";
}

&main(@ARGV);
