#!/usr/bin/perl
use strict;
use warnings;

sub run(@){
  print "@_\n";
  system @_;
}

sub main(@){
  my $host = `n9`;
  chomp $host;
  run "scp", "$ENV{HOME}/.secrets", "user\@$host:/home/user";
}

&main(@ARGV);
