#!/usr/bin/perl
use strict;
use warnings;

sub run(@){
  print "@_\n";
  system @_;
}

sub main(@){
  my $host = `n9`;
  chomp $host;
  run "rsync", "-avP",
    "--exclude=status",
    "$ENV{HOME}/openvpn",
    "user\@$host:/home/user";
  run "scp", "$ENV{HOME}/.twip", "user\@$host:/home/user";
}
&main(@ARGV);
