#!/usr/bin/perl
use strict;
use warnings;

my $host = '192.168.2.15';

my $sshDefaultFileName = '/tmp/sshDefaultFile';
my $sshDefaultFileContent =
'# Default settings for openssh-server. This file is sourced by /bin/sh from
# /etc/init.d/ssh.

# Options to pass to sshd
SSHD_OPTS="-D -4"

# OOM-killer adjustment for sshd (see
# linux/Documentation/filesystems/proc.txt; lower values reduce likelihood
# of being killed, while -17 means the OOM-killer will ignore sshd; set to
# the empty string to skip adjustment)
SSHD_OOM_ADJUST=-17

mkdir -m 0755 -p /var/run/sshd
exec /usr/sbin/sshd $SSHD_OPTS
';


my $commandScriptFileName = '/tmp/commandScript.sh';
my $commandScriptFileContent =
qq@#!/bin/sh

set -x
echo type a new root password
passwd

diff /etc/default/ssh $sshDefaultFileName
cp $sshDefaultFileName /etc/default/ssh

sshdConf=/etc/ssh/sshd_config
tmpFile=/tmp/sshd_config.tmp
echo "\\n\\n"
echo change PermitRootLogin from no to yes
cat \$sshdConf | sed 's/PermitRootLogin no/PermitRootLogin yes/' > \$tmpFile
diff \$sshdConf \$tmpFile
cp \$tmpFile \$sshdConf

echo delete user password
passwd -d user

killall sshd
@;


system 'ssh-keygen', '-f', "$ENV{HOME}/.ssh/known_hosts", '-R', '192.168.2.15';
system 'ssh-keygen', '-f', "$ENV{HOME}/.ssh/known_hosts", '-R', `n9 --host`;
system 'sudo', 'ifconfig', 'usb0', '192.168.2.14', 'netmask', '255.255.255.0', 'up';

open FH, "> $sshDefaultFileName"
  or die "Couldnt open $sshDefaultFileName for writing\n";
print FH $sshDefaultFileContent;
close FH;
system 'scp', $sshDefaultFileName, "user\@$host:$sshDefaultFileName";

open FH, "> $commandScriptFileName"
  or die "Couldnt open $commandScriptFileName for writing\n";
print FH $commandScriptFileContent;
close FH;
system 'scp', $commandScriptFileName, "user\@$host:$commandScriptFileName";

print "devel-su passwd {starts as rootme}\n";
system 'ssh', "user\@$host", "devel-su -c 'sh $commandScriptFileName'";
