#!/usr/bin/perl
use strict;
use warnings;

my $arg = shift();
die "Usage: $0 [backup|restore]\n" if $arg !~ /^(backup|restore)$/;

my $host = `n9`;
chomp $host;

my $dir = "$ENV{HOME}/Code/n9";
my $localDir = "$dir/qtodo";
my $remoteDir = "/home/user/to-do-o";

my $local = $localDir;
my $remote = "user\@$host:$remoteDir";

my @excludes = qw(
  cache
);

my @rsyncOpts = qw(
  -a --no-owner --no-group
  -v -P
  --del
);
for my $exclude(@excludes){
  push @rsyncOpts, "--exclude=$exclude";
}

sub run(@){
  print "@_\n";
  system @_;
  die "failed" if $? != 0;
}

system "n9", "-s", "mkdir $remoteDir; chown user.users $remoteDir";
if($arg eq 'backup'){
  run "rsync", @rsyncOpts, "$remote/", $local;
}elsif($arg eq 'restore'){
  run "rsync", @rsyncOpts, "$local/", $remote;
}

