#!/usr/bin/perl
use strict;
use warnings;

sub run(@);

my $dir = "$ENV{HOME}/Code/n9";
my $myDocsLocal = "$dir/backup/MyDocs";
my $myDocsRemote = "/home/user/MyDocs";

my @excludes = map {"--exclude=$_"} qw(
  monav_data

  DCIM
  DCIM-pixmirror

  Music

  email

  backup-contacts
  backup-sms
  backup-sms-repo
  backup-call
  backup-call-repo
  backup-tracker

  cities
  DevIcon.fil
  ignored/
  Playlists
  pvr_hwrec
  .thumbnails/
  .qf
  .wallpapers/
  lost+found
);

my @rsyncOpts = qw(
  -a --no-owner --no-group
  -v -P
);

sub main(@){
  my $overwrite = 0;
  $overwrite = shift if @_ == 1 and $_[0] =~ /--overwrite/;
  die "Usage: $0 [--overwrite]\n" if @_ > 0;

  my $host = `n9`;
  chomp $host;

  my $local = $myDocsLocal;
  my $remote = "user\@$host:$myDocsRemote";

  if($overwrite){
    run "rsync", @rsyncOpts, @excludes, "$local/", $remote, "--del", "-n";
    print "dryrun ok? [Y/n] ";
    if(<STDIN> !~ /n/){
      run "rsync", @rsyncOpts, @excludes, "$local/", $remote, "--del";
    }
  }else{
    run "rsync", @rsyncOpts, @excludes, "$remote/", $local;
    run "rsync", @rsyncOpts, @excludes, "$local/", $remote;
  }
}


sub run(@){
  print "@_\n";
  system @_;
  die "failed" if $? != 0;
}

&main(@ARGV);
