#!/usr/bin/perl
use strict;
use warnings;

sub run(@);

my $dir = "$ENV{HOME}/Code/n9";
my $mmsLocal = "$dir/backup/backup-mms";
my $mmsRemote = "/home/user/.mms";

my @rsyncOpts = qw(
  -a --no-owner --no-group
  -v -P
  --exclude=private/
);

sub main(@){
  my $host = `n9`;
  chomp $host;

  my $local = $mmsLocal;
  my $remote = "user\@$host:$mmsRemote";

  run "rsync @rsyncOpts $remote/* $local/";

  run "rsync @rsyncOpts $local/* $remote/";

  print "\n\n";
  run "n9", "-u", "user", "mms-symlinks";
}

sub run(@){
  print "@_\n";
  system @_;
  die "ERROR: \"@_\" failed" if $? != 0;
}

&main(@ARGV);
