#!/usr/bin/perl
use strict;
use warnings;

my $host = `n9`;
chomp $host;

my $dir = "$ENV{HOME}/Code/n9";
my $myDocsLocal = "$dir/backup/MyDocs";
my $myDocsRemote = "/home/user/MyDocs";

my $local = $myDocsLocal;
my $remote = "user\@$host:$myDocsRemote";

my @excludes = qw(
  DCIM
  DCIM-pixmirror

  Music

  backup-contacts
  backup-sms
  backup-call
  backup-tracker

  cities
  DevIcon.fil
  Playlists
  pvr_hwrec
  .thumbnails/
  .qf
  .wallpapers/
  lost+found
);

my @rsyncOpts = qw(
  -a --no-owner --no-group
  -v -P
);
for my $exclude(@excludes){
  push @rsyncOpts, "--exclude=$exclude";
}

sub run(@){
  print "@_\n";
  system @_;
  die "failed" if $? != 0;
}

run "rsync", @rsyncOpts, "$remote/", $local;
run "rsync", @rsyncOpts, "$local/", $remote;

