#!/usr/bin/perl
use strict;
use warnings;

my $host = `n9`;
chomp $host;

my $dir = "$ENV{HOME}/Code/n9";
my $mozillaLocal = "$dir/mozilla";
my $mozillaRemote = "/home/user/.mozilla";

my $local = $mozillaLocal;
my $remote = "user\@$host:$mozillaRemote";

my @excludes = qw();

my @rsyncOpts = qw(
  -a --no-owner --no-group
  -v
);
for my $exclude(@excludes){
  push @rsyncOpts, "--exclude=$exclude";
}

sub run(@){
  print "@_\n";
  system @_;
}

run "rsync", @rsyncOpts, "$remote/", $local;
run "rsync", @rsyncOpts, "$local/", $remote;

