#!/usr/bin/perl
use strict;
use warnings;

die "Usage: $0 path path path" if @ARGV == 0 or $ARGV[0] =~ /^(-h|--help)$/;
my $host = `n9`;
chomp $host;

sub run(@){
  print "@_\n";
  system @_;
}

for my $p(@ARGV){
  my $boingP = `boing $p`;
  chomp $boingP;
  run "rsync", "-avP", "root\@$host:$p", $boingP;
}
