#!/usr/bin/perl
use strict;
use warnings;

my $tmpFile = "/tmp/ubiboot-expect-command";

sub main(@){
  my $cmd = "@_";
  system qw(sudo ifconfig usb0 up);
  system qw(sudo ifconfig usb0 192.168.2.14);
  open FH, "> $tmpFile" or die "Couldnt write $tmpFile\n";
  print FH ''
    . "spawn telnet 192.168.2.15\n"
    . "expect -e \"/ #\"\n"
    . "send \"$cmd\\n\"\n"
    . "expect -e \"/ #\"\n"
    . "send \"exit\\n\"\n"
    ;
  close FH;
  system "expect", "-f", $tmpFile;
}

&main(@ARGV);
