#!/usr/bin/perl
use strict;
use warnings;

my $srcDir = "$ENV{HOME}/.ssh";
my $homeMntDir = "/media/n9-home";
my $rootMntDir = "/media/n9-root";
my $uidGid = "29999.29999";

sub run(@){
  print "@_\n";
  system @_;
}

sub sshkeys($){
  my $sshDir = shift;
  run "sudo", "mkdir", "-p", $sshDir;
  run "cat $srcDir/*.pub | sudo tee $sshDir/authorized_keys > /dev/null";
}

sub main(@){
  die "Usage: $0\n" if @_ != 0;
  print "installing authkeys for root:\n";
  sshkeys "$rootMntDir/root/.ssh";
  print "\n\n";

  print "installing authkeys for user:\n";
  my $preDir = "$homeMntDir/preinstalled";
  my $userDir = "$homeMntDir/user";
  if(-d $preDir and not -d $userDir){
    print "before initial boot, setting up $preDir\n";
    sshkeys "$preDir/.ssh";
  }elsif(not -d $preDir and -d $userDir){
    print "after initial boot, setting up user .ssh dir\n";
    sshkeys "$userDir/.ssh";
    run "sudo", "chown", $uidGid, "$userDir/.ssh/authorized_keys";
  }else{
    die "Error: could not determine initial boot status\n";
  }
}

&main(@ARGV);
